# Generated by Django 6.0.4 on 2026-04-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_remove_user_groups_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
