# Generated by Django 6.0.4 on 2026-06-02 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        ('events', '0002_event_is_public'),
        ('register', '0009_alter_user_id'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS `like_like` (
                `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
                `user_id` BIGINT NOT NULL,
                `like_type` VARCHAR(20) NOT NULL,
                `event_id` BIGINT NULL,
                `comment_id` BIGINT NULL,
                `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT `like_like_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `register_user`(`id`) ON DELETE CASCADE,
                CONSTRAINT `like_like_event_id_fkey` FOREIGN KEY (`event_id`) REFERENCES `events_event`(`id`) ON DELETE CASCADE,
                CONSTRAINT `like_like_comment_id_fkey` FOREIGN KEY (`comment_id`) REFERENCES `comment_comment`(`id`) ON DELETE CASCADE,
                UNIQUE KEY `like_like_user_id_like_type_event_id_comment_id_uniq` (`user_id`, `like_type`, `event_id`, `comment_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
            """,
            reverse_sql="DROP TABLE IF EXISTS `like_like`;"
        ),
    ]