# Generated by Django 6.0.4 on 2026-06-15 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_event_favorite_count'),
        ('register', '0009_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='events.event', verbose_name='活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='register.user', verbose_name='用户')),
            ],
            options={
                'db_table': 'favorite_favorite',
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
            },
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'event')},
        ),
    ]