# Generated by Django 6.0.4 on 2026-06-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
    ]
