# Generated by Django 6.0.4 on 2026-06-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]