# Generated by Django 6.0.4 on 2026-06-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='favorite_count',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
    ]