# Generated by Django 6.0.4 on 2026-06-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_favorite_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enroll_count',
            field=models.IntegerField(default=0, verbose_name='报名数'),
        ),
    ]