# Generated by Django 6.0.4 on 2026-06-04 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_event_like_count'),
        ('register', '0009_alter_user_id'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS `favorie_favorite` (
                `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
                `user_id` BIGINT NOT NULL,
                `event_id` BIGINT NOT NULL,
                `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT `favorie_favorite_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `register_user`(`id`) ON DELETE CASCADE,
                CONSTRAINT `favorie_favorite_event_id_fkey` FOREIGN KEY (`event_id`) REFERENCES `events_event`(`id`) ON DELETE CASCADE,
                UNIQUE KEY `favorie_favorite_user_id_event_id_uniq` (`user_id`, `event_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
            """,
            reverse_sql="DROP TABLE IF EXISTS `favorie_favorite`;"
        ),
    ]